name: example_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # BSD
  intl: 0.17.0

  cupertino_icons: 1.0.5

  google_maps_flutter: 2.3.0
  flutter_map: 4.0.0
  geolocator: 9.0.1
  app_settings: 4.1.8

  flutter_signin_button: ^2.0.0
  dropdown_button2: ^1.6.3

  firebase_core: 2.11.0
  firebase_auth: 4.3.0
  cloud_firestore: 4.4.5

  google_sign_in: 6.0.2
  fluttertoast: 8.0.9

  flutter_stripe: ^9.2.1
  flutter_stripe_web: ^4.1.1
  stripe_checkout: ^1.0.1
  pay: ^1.1.0

  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1


flutter_intl:
  enabled: true
  main_locale: uk_UA

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png